### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by pclucas14** [r-three/routing#1]
Hi, 

Thanks for open sourcing your code. I am trying to replicate the T5 experiments, but [the following import ](https://github.com/r-three/smear/blob/main/hyperformer/hyperformer/third_party/models/modeling_t5_v1_1.py#L19)is giving me an error

```
from hyperformer.adapters.lora_controller import LoRAController
```

Is it possible there is a file missing ? 

Thank you

**Comment by muqeeth** [comment]
Hey, I was experimenting with SMEAR on other styles of adapters like LoRA and IA3. However, as the Adapters are closely related to FFNs, we decided to stick with them in this work. I have updated the code to remove these references. Please let me know if you come across any issues :)

Additionally, we experimented with SMEAR on both T5-small and T5-Base models. If you are considering running experiments with higher model dimensions, I found this helpful in my current experiments: [https://github.com/r-three/smear/blob/8c3a3949b317286353fc1ddc795c6c236a21498f/hyperformer/hyperformer/adapters/adapter_utils.py#L154](https://github.com/r-three/smear/blob/8c3a3949b317286353fc1ddc795c6c236a21498f/hyperformer/hyperformer/adapters/adapter_utils.py#L154).

**Comment by pclucas14** [comment]
Thank for the quick answer, it works now :)

**Comment by pclucas14** [comment]
Do you have any intuition as to how smear manages to process more examples per second as Latent Skills ? From the looks of it, the adapter logic is the same, only the adapter probabilities are obtained differently. Given that Latent Skills uses a lookup table + normalization (compared to a matmul + normalization), I would have thought it would have been at least as fast as SMEAR.

**Comment by muqeeth** [comment]
Yes, that's correct. The speed should be almost the same as latent skills. I think the differences are probably due to GPU optimization.

**Comment by pclucas14** [comment]
Ok I see, thanks
